---
- name: Apt role
  apt:
    name: "{{ item.apt_name | default(item.name) }}"
    state: "{{ item.state | default(package_state) }}"
    update_cache: "{{ package_update_cache }}"
  when: (item.apt_ignore|default('no'))|string in 'No,no'
  with_items: "{{ package_list }}"
